In [2]:
import gzip
import os
import datetime
import tensorflow as tf
import numpy as np
from tqdm import tqdm_notebook

In [3]:
sess = None

def reset_tf(sess = None, log_device_placement = False):
    if sess:
        sess.close()
    tf.reset_default_graph()
    tf.set_random_seed(0)
    return tf.InteractiveSession(config = tf.ConfigProto(log_device_placement = log_device_placement))

def dump_statistics():
    total_parameters = 0
    for variable in tf.trainable_variables():
        # shape is an array of tf.Dimension
        shape = variable.get_shape()
        variable_parameters = 1
        for dim in shape:
            variable_parameters *= dim.value
        print('parameters for "%s": %d' % (variable.name, variable_parameters))
        total_parameters += variable_parameters
    print('total parameters: %d' % total_parameters)

In [4]:
class HyperParameters:
    learning_rate = 1e-3
    
    dropout_rate = 0.2
    
    context_size = 850
    question_size = 60
    answers_size = 6
    
    d_hidden = 75
    
    num_rnn_layers_contexts = 1
    num_rnn_layers_questions = 1

    dataset_batch_size = 80
    dataset_num_parallel_calls = 2
    dataset_prefetch_size = 256
    dataset_shuffle_size = 512
    
    gradient_clip_norm = 5.0

In [5]:
class RnnModel:
    def __init__(self, session, word_embeddings, hparams):
        self._session = session
        self._word_embeddings = word_embeddings
        self._hparams = hparams
        
    def _parse_example(self, example_proto):
        # parse proto
        parsed = tf.parse_single_example(example_proto, features = {
            'context': tf.VarLenFeature(tf.int64),
            'question': tf.VarLenFeature(tf.int64),
            'answer_starts': tf.VarLenFeature(tf.int64),
            'answer_ends': tf.VarLenFeature(tf.int64), })
        
        # convert to dense tensors
        context = tf.sparse_tensor_to_dense(parsed['context'])
        question = tf.sparse_tensor_to_dense(parsed['question'])
        answer_starts = tf.sparse_tensor_to_dense(parsed['answer_starts'])
        answer_ends = tf.sparse_tensor_to_dense(parsed['answer_ends'])
        
        # pad tensors
        context_len = tf.shape(context)[0]
        question_len = tf.shape(question)[0]
        answers_len = tf.shape(answer_starts)[0]
        zero_vector = self._word_embeddings.shape[0] - 1
        context = tf.pad(
            context,
            [[0, self._hparams.context_size - context_len]],
            constant_values = 0)
        question = tf.pad(
            question,
            [[0, self._hparams.question_size - question_len]],
            constant_values = 0)
        answer_starts = tf.pad(
            answer_starts,
            [[0, self._hparams.answers_size - answers_len]],
            constant_values = -1)
        answer_ends = tf.pad(
            answer_ends,
            [[0, self._hparams.answers_size - answers_len]],
            constant_values = -1)
        
        return (context, context_len, question, question_len, answer_starts, answer_ends)
    
    def _build_dataset_pipeline(self):
        with tf.variable_scope('dataset'):
            # placeholders
            self._dataset_filenames = tf.placeholder(
                tf.string,
                shape = [None],
                name = 'dataset_filenames')
            self._dataset_limit = tf.placeholder_with_default(
                tf.constant(-1, tf.int64),
                shape = [],
                name = 'dataset_limit')
            self._dataset_shuffle_size = tf.placeholder_with_default(
                tf.constant(self._hparams.dataset_batch_size, tf.int64),
                shape = [],
                name = 'dataset_shuffle_size')
            self._dataset_batch_size = tf.placeholder_with_default(
                tf.constant(self._hparams.dataset_batch_size, tf.int64),
                shape = [],
                name = 'dataset_batch_size')
            self._dataset_prefetch_size = tf.placeholder_with_default(
                tf.constant(self._hparams.dataset_prefetch_size, tf.int64),
                shape = [],
                name = 'dataset_prefetch_size')

            # build dataset
            dataset = tf.data.TFRecordDataset(
                tf.random_shuffle(self._dataset_filenames),
                compression_type='GZIP')
            dataset = dataset.take(self._dataset_limit)
            dataset = dataset.map(
                self._parse_example,
                num_parallel_calls = self._hparams.dataset_num_parallel_calls)
            dataset = dataset.shuffle(self._dataset_shuffle_size)
            dataset = dataset.prefetch(self._dataset_prefetch_size)
            dataset = dataset.batch(self._dataset_batch_size)

            # build iterator
            self._dataset_iterator = dataset.make_initializable_iterator()
            (contexts,
             context_lens,
             questions,
             question_lens,
             answer_starts,
             answer_ends) = self._dataset_iterator.get_next()
            
            # trim contexts/questions
            self._context_max_len = tf.reduce_max(context_lens)
            self._question_max_len = tf.reduce_max(question_lens)
            contexts = contexts[:, :self._context_max_len]
            questions = questions[:, :self._question_max_len]
            
            # give key tensors names
            self._contexts = tf.identity(contexts, 'contexts')
            self._context_lens = tf.identity(context_lens, 'context_lens')
            self._questions = tf.identity(questions, 'questions')
            self._question_lens = tf.identity(question_lens, 'question_lens')
            self._answer_starts = tf.identity(answer_starts, 'answer_starts')
            self._answer_ends = tf.identity(answer_ends, 'answer_ends')

            # minibatch size
            self._minibatch_size = tf.shape(self._contexts)[0]
            self._minibatch_size = tf.identity(self._minibatch_size, 'minibatch_size')
            
    def _rnn_uni_layer(self, seqs, num_layers, size):
        # GRU
        def build_gru(dropout):
            return tf.contrib.cudnn_rnn.CudnnGRU(
                num_layers = num_layers,
                num_units = size,
                input_size = seqs.shape[-1].value,
                dropout = dropout,
                direction = 'unidirectional')
        gru_with_dropout = build_gru(self._hparams.dropout_rate)
        gru_without_dropout = build_gru(0.0)

        # variables
        gru_params = tf.get_variable(
            'gru_params',
            [gru_with_dropout.params_size().eval(session = self._session)])

        # make input hidden state
        input_h = tf.zeros([num_layers, self._minibatch_size, size])

        # make input data time-major
        input_data = tf.transpose(seqs, perm = [1, 0, 2])
        
        # run GRU
        outputs = tf.cond(
            self._training,
            lambda: gru_with_dropout(input_data, input_h, gru_params)[0],
            lambda: gru_without_dropout(input_data, input_h, gru_params)[0])
        
        # undo time-major
        outputs = tf.transpose(outputs, perm = [1, 0, 2])
        
        return outputs
    
    def _rnn_bidir_layer(self, seqs, seq_lens, num_layers, size):
        # reverse input for backwards RNN
        seqs_fw = seqs
        seqs_bk = tf.reverse_sequence(seqs, seq_lens, seq_axis = 1)

        # run RNNs
        with tf.variable_scope('fw'):
            out_fw = self._rnn_uni_layer(seqs_fw, num_layers, size)
        with tf.variable_scope('bk'):
            out_bk = self._rnn_uni_layer(seqs_bk, num_layers, size)

        # unreverse output
        out_bk = tf.reverse_sequence(out_bk, seq_lens, seq_axis = 1)
        
        # concat
        return tf.concat([out_fw, out_bk], axis = -1)
    
    def _self_attention(self, layer, project = False):
        l = layer
        size = l.shape[-1].value
        
        if project:
            l = tf.layers.dense(l, size, use_bias = False, name = 'proj')

        # compute weights
        l_T = tf.transpose(l, perm = [0, 2, 1])
        w = tf.matmul(l, l_T)
        w /= np.sqrt(size)
        
        # mask self-attention
        mask = tf.diag(tf.fill([tf.shape(layer)[1]], -1e25))
        mask = tf.expand_dims(mask, axis = 0)
        w += mask
        
        # softmax
        w = tf.nn.softmax(w, name = 'weights')

        # dropout
        w = tf.layers.dropout(
            w,
            rate = self._hparams.dropout_rate,
            training = self._training)

        # apply weights
        return tf.matmul(w, layer)
    
    def _cross_attention(self, c, q):
        size = c.shape[-1].value
        assert q.shape[-1].value == size
        
        # project
        cw = tf.layers.dense(c, size, use_bias = False, name = 'proj_cw')
        qw = tf.layers.dense(q, size, use_bias = False, name = 'proj_qw')

        # compute weights
        qw_T = tf.transpose(qw, perm = [0, 2, 1])           # [batch, size, q_len]
        w = tf.matmul(cw, qw_T)                             # [batch, c_len, q_len]
        w /= np.sqrt(size)
        
        # c2q weights
        w_c2q = tf.nn.softmax(w)
        w_c2q = tf.layers.dropout(
            w_c2q,
            rate = self._hparams.dropout_rate,
            training = self._training)

        # q2c weights
        w_q2c = tf.transpose(w, perm = [0, 2, 1])           # [batch, q_len, c_len]
        w_q2c = tf.nn.softmax(w_q2c)
        w_q2c = tf.layers.dropout(
            w_q2c,
            rate = self._hparams.dropout_rate,
            training = self._training)

        # apply weights
        c2q = tf.matmul(w_c2q, q)
        q2c = tf.matmul(w_q2c, c)
        
        return c2q, q2c
                
    def _layer_norm(self, layer, epsilon = 1e-6, name = 'ln'):
        with tf.variable_scope(name):
            size = layer.shape[-1].value
            scale = tf.get_variable(
                'scale',
                [size],
                initializer = tf.ones_initializer())
            bias = tf.get_variable(
                'bias',
                [size],
                initializer = tf.zeros_initializer())
            mean = tf.reduce_mean(
                layer,
                axis = -1,
                keep_dims = True)
            variance = tf.reduce_mean(
                tf.square(layer - mean),
                axis = -1,
                keep_dims = True)
            norm_layer = (layer - mean) * tf.rsqrt(variance + epsilon)
            return norm_layer * scale + bias
        
    def _build_model(self):
        with tf.variable_scope('model'):
            # placeholders
            self._training = tf.placeholder(tf.bool, name = 'training')
            
            # init embedding
            word_embeddings = tf.get_variable(
                name = "word_embeddings",
                shape = self._word_embeddings.shape,
                initializer = tf.constant_initializer(self._word_embeddings),
                trainable = False)
            
            # embed contexts/questions
            contexts_embedded = tf.nn.embedding_lookup(
                word_embeddings,
                self._contexts)
            questions_embedded = tf.nn.embedding_lookup(
                word_embeddings,
                self._questions)
            
            # RNN contexts/questions
            with tf.variable_scope('encode_rnn'):
                contexts_encoded = self._rnn_bidir_layer(
                    contexts_embedded,
                    self._context_lens,
                    self._hparams.num_rnn_layers_contexts,
                    self._hparams.d_hidden)
            with tf.variable_scope('encode_rnn', reuse = True):
                questions_encoded = self._rnn_bidir_layer(
                    questions_embedded,
                    self._question_lens,
                    self._hparams.num_rnn_layers_questions,
                    self._hparams.d_hidden)
                    
            # apply masks
            contexts_mask = tf.sequence_mask(
                self._context_lens,
                maxlen = self._context_max_len,
                dtype = tf.float32)
            contexts_mask_exp = tf.expand_dims(contexts_mask, axis = -1)
            contexts_encoded *= contexts_mask_exp
            questions_mask = tf.sequence_mask(
                self._question_lens,
                maxlen = self._question_max_len,
                dtype = tf.float32)
            questions_mask_exp = tf.expand_dims(questions_mask, axis = -1)
            questions_encoded *= questions_mask_exp

            # summarize question
            with tf.variable_scope('question_summary'):
                q = self._layer_norm(questions_encoded)
                q = tf.layers.dropout(
                    q,
                    rate = self._hparams.dropout_rate,
                    training = self._training)
                weights = tf.layers.dense(q, 1, use_bias = False)   # [batch_size, query_size, 1]
                weights = tf.squeeze(weights, axis = -1)
                weights = tf.nn.softmax(weights)
                weights = tf.expand_dims(weights, axis = -1)
                question_summary = questions_encoded * weights      # [batch_size, question_size, d_hidden]
                question_summary = tf.reduce_sum(                   # [batch_size, d_hidden]
                    question_summary,
                    axis = 1)
                
            # joint attention layer
            with tf.variable_scope('joint_attn'):
                c2q, q2c = self._cross_attention(contexts_encoded, questions_encoded)
                joint_encoded = tf.concat(
                    [contexts_encoded, c2q],
                    axis = -1)
                
            # joint self-attention layer
            with tf.variable_scope('joint_self_attn'):
                attn = self._self_attention(joint_encoded)
                q = tf.expand_dims(question_summary, 1)
                q = tf.tile(q, [1, self._context_max_len, 1])
                joint_encoded = tf.concat(
                    [joint_encoded, attn, q],
                    axis = -1)
                joint_encoded *= contexts_mask_exp
            
            # joint RNN layer
            with tf.variable_scope('joint_rnn'):
                joint_encoded = self._rnn_bidir_layer(
                    joint_encoded,
                    self._context_lens,
                    1,
                    self._hparams.d_hidden)
                
            # compute answer pointers
            with tf.variable_scope('answer'):
                q = self._layer_norm(question_summary, name = 'ln_q')
                q = tf.layers.dropout(
                    q,
                    rate = self._hparams.dropout_rate,
                    training = self._training)
                q = tf.layers.dense(q, joint_encoded.shape[-1].value)
                q = tf.expand_dims(q, axis = -1)                # [batch_size, d_hidden, 1]
                l = tf.matmul(joint_encoded, q)                 # [batch_size, context_size, 1]
                l = tf.squeeze(l, axis = -1)                    # [batch_size, context_size]
                l *= contexts_mask
                self._answer_start_logits = l

#             self._answer_end_logits = tf.layers.dense(
#                 joint_layer,
#                 1,
#                 use_bias = False,
#                 name = 'answer_end_logits')
#             self._answer_end_logits = tf.squeeze(      # [batch_size, context_size]
#                 self._answer_end_logits,
#                 axis = -1,
#                 name = 'answer_end_logits')

    def _build_optimizer(self):
        with tf.variable_scope('optimize'):
            # individual losses
            # TODO: incorporate other answers into training
            l0 = tf.nn.sparse_softmax_cross_entropy_with_logits(
                labels = self._answer_starts[:, 0],
                logits = self._answer_start_logits)
#             l1 = tf.nn.sparse_softmax_cross_entropy_with_logits(
#                 labels = self._answer_ends[:, 0],
#                 logits = self._answer_end_logits)

            # total loss
            self._total_loss = tf.reduce_sum(l0) # + tf.reduce_sum(l1)
            self._total_loss = tf.identity(self._total_loss, 'total_loss')
            
            # mean loss
            self._mean_loss = self._total_loss / tf.cast(self._minibatch_size, tf.float32)
            self._mean_loss = tf.identity(self._mean_loss, 'mean_loss')
            
            # start/end probabilities/estimates
            self._answer_start_probs = tf.nn.softmax(
                self._answer_start_logits,
                name = 'answer_start_logits')
            self._answer_start_estimates = tf.argmax(
                self._answer_start_probs,
                axis = -1,
                name = 'answer_start_estimates')
#             self._answer_end_probs = tf.nn.softmax(
#                 self._answer_end_logits,
#                 name = 'answer_end_logits')
#             # N.B., mask impossible answers
#             mask = 1.0 - tf.sequence_mask(
#                 self._answer_start_estimates,
#                 self._hparams.context_size,
#                 dtype = tf.float32)
#             self._answer_end_estimates = tf.argmax(
#                 mask * self._answer_end_probs,
#                 axis = -1,
#                 name = 'answer_end_estimates')
            
            # exact match accuracy
            answer_starts_eq = tf.equal(
                self._answer_starts[:, 0],
                self._answer_start_estimates)
            self._total_exact_matches = tf.reduce_sum(
                tf.cast(answer_starts_eq, tf.int64),
                name = 'total_exact_matches')
#             answer_ends_eq = tf.equal(
#                 self._answer_ends[:, 0],
#                 self._answer_end_estimates)
#             answers_eq = tf.logical_and(
#                 answer_starts_eq,
#                 answer_ends_eq)
#             self._total_exact_matches = tf.reduce_sum(
#                 tf.cast(answers_eq, tf.int64),
#                 name = 'total_exact_matches')
            
#             # F1
#             a0 = self._answer_starts[:, 0]
#             a1 = self._answer_ends[:, 0] + 1
#             answer_lens = a1 - a0
#             b0 = self._answer_start_estimates
#             b1 = self._answer_end_estimates + 1
#             answer_estimate_lens = b1 - b0
#             tps = tf.maximum(
#                 tf.cast(0, tf.int64),
#                 tf.minimum(a1, b1) - tf.maximum(a0, b0))
#             fps = answer_estimate_lens - tps
#             fns = answer_lens - tps
#             self._total_true_positives = tf.reduce_sum(
#                 tps,
#                 name = 'total_true_positives')
#             self._total_false_positives = tf.reduce_sum(
#                 fps,
#                 name = 'total_false_positives')
#             self._total_false_negatives = tf.reduce_sum(
#                 fns,
#                 name = 'total_false_negatives')
            self._total_true_positives = tf.constant(0)
            self._total_false_positives = tf.constant(0)
            self._total_false_negatives = tf.constant(0)

            # learning rate placeholder
            self._learning_rate = tf.placeholder_with_default(
                tf.constant(self._hparams.learning_rate, tf.float32),
                shape = [],
                name = 'learning_rate')
            
            update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
            with tf.control_dependencies(update_ops):
                self._global_step = tf.Variable(0, name = 'global_step', trainable = False)
                self._optimizer = tf.train.AdamOptimizer(learning_rate = self._learning_rate)
                
                # gradient clipping
                gradients, variables = zip(*self._optimizer.compute_gradients(self._mean_loss))
                gradients, _ = tf.clip_by_global_norm(
                    gradients, 
                    self._hparams.gradient_clip_norm)
                
                self._train_op = self._optimizer.apply_gradients(
                    zip(gradients, variables),
                    global_step = self._global_step)

    def process(self,
                dataset_filenames,
                dataset_limit = -1,
                learning_rate = None,
                header = 'results',
                train = False,
                log_file = None):
        # initialize dataset to files
        self._session.run(self._dataset_iterator.initializer, feed_dict={
            self._dataset_filenames: dataset_filenames,
            self._dataset_limit: dataset_limit })
        
        if learning_rate is None:
            learning_rate = self._hparams.learning_rate

        cum_loss = 0
        cum_num_examples = 0
        cum_exact_matches = 0
        cum_tps = 0
        cum_fps = 0
        cum_fns = 0
        
        # start progress
        start = datetime.datetime.now()
        progress = tqdm_notebook(leave = False, desc = header)

        while True:
            # process a minibatch
            try:
                (_,
                 curr_total_loss,
                 curr_exact_matches,
                 curr_tps,
                 curr_fps,
                 curr_fns,
                 curr_minibatch_size) = self._session.run(
                    (self._train_op if train else (),
                     self._total_loss,
                     self._total_exact_matches,
                     self._total_true_positives,
                     self._total_false_positives,
                     self._total_false_negatives,
                     self._minibatch_size),
                    feed_dict = {
                        self._training: train,
                        self._learning_rate: learning_rate })
            except tf.errors.OutOfRangeError:
                break

            # update loss stats
            cum_loss += curr_total_loss
            cum_exact_matches += curr_exact_matches
            cum_tps += curr_tps
            cum_fps += curr_fps
            cum_fns += curr_fns
            cum_num_examples += curr_minibatch_size
            
            # update progress
            progress.update(curr_minibatch_size)
            progress.set_postfix(loss = cum_loss / cum_num_examples)

        # end progress
        progress.close()
        finish = datetime.datetime.now()
        
        # precision
        precision = 0
        if cum_tps + cum_fps > 0:
            precision = cum_tps / (cum_tps + cum_fps)
            
        # recall
        recall = 0
        if cum_tps + cum_fns > 0:
            recall = cum_tps / (cum_tps + cum_fns)
            
        # F1
        F1 = 0
        if precision + recall > 0:
            F1 = 2 * precision * recall / (precision + recall)
        
        # print/log output
        message = '%s: time=%s, step=%d, loss=%g, exact_match=%g, precision=%g, recall=%g, F1=%g' % (
            header,
            finish - start,
            tf.train.global_step(sess, self._global_step),
            cum_loss / cum_num_examples,
            cum_exact_matches / cum_num_examples,
            precision,
            recall,
            F1)
        print(message)
        if log_file:
            print(message, file=log_file)
            log_file.flush()

In [6]:
with gzip.open('../../data/SQuAD/data_1.vocab.embeddings.npy.gz', 'rb') as f:
    word_embeddings = np.load(f)

In [7]:
def list_files(path):
    return sorted([os.path.join(path, file) for file in os.listdir(path)])

train_set = list_files('../../data/SQuAD/data_1.train')
dev_set = list_files('../../data/SQuAD/data_1.dev')

In [10]:
sess = reset_tf(sess)

model = RnnModel(sess, word_embeddings, HyperParameters())
model._build_dataset_pipeline()
model._build_model()
model._build_optimizer()
dump_statistics()

parameters for "model/encode_rnn/fw/gru_params:0": 84825
parameters for "model/encode_rnn/bk/gru_params:0": 84825
parameters for "model/question_summary/ln/scale:0": 150
parameters for "model/question_summary/ln/bias:0": 150
parameters for "model/question_summary/dense/kernel:0": 150
parameters for "model/joint_attn/proj_cw/kernel:0": 22500
parameters for "model/joint_attn/proj_qw/kernel:0": 22500
parameters for "model/joint_rnn/fw/gru_params:0": 186075
parameters for "model/joint_rnn/bk/gru_params:0": 186075
parameters for "model/answer/ln_q/scale:0": 150
parameters for "model/answer/ln_q/bias:0": 150
parameters for "model/answer/dense/kernel:0": 22500
parameters for "model/answer/dense/bias:0": 150
total parameters: 610200


In [11]:
sess.run(tf.global_variables_initializer())

In [ ]:
with open('../../logs/SQuAD/model_rnn_4.2.log', 'wt') as f:
    for i in range(50):
        model.process(
            train_set,
            header = 'train_%d' % i,
            train = True,
            log_file = f)
        model.process(
            dev_set,
            header = 'dev_%d' % i,
            train = False,
            log_file = f)

HBox(children=(IntProgress(value=1, bar_style='info', description='train_0', max=1), HTML(value='')))

train_0: time=0:04:18.711854, step=1095, loss=3.2797, exact_match=0.207103, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_0', max=1), HTML(value='')))

dev_0: time=0:00:13.470105, step=1095, loss=2.93637, exact_match=0.253075, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_1', max=1), HTML(value='')))

train_1: time=0:04:20.230364, step=2190, loss=2.65119, exact_match=0.312401, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_1', max=1), HTML(value='')))

dev_1: time=0:00:13.288354, step=2190, loss=2.58648, exact_match=0.323841, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_2', max=1), HTML(value='')))

train_2: time=0:04:12.916900, step=3285, loss=2.33096, exact_match=0.380198, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_2', max=1), HTML(value='')))

dev_2: time=0:00:13.318368, step=3285, loss=2.42106, exact_match=0.367455, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_3', max=1), HTML(value='')))

train_3: time=0:04:12.694991, step=4380, loss=2.09165, exact_match=0.433087, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_3', max=1), HTML(value='')))

dev_3: time=0:00:13.209056, step=4380, loss=2.28833, exact_match=0.394986, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_4', max=1), HTML(value='')))

train_4: time=0:04:12.699345, step=5475, loss=1.89022, exact_match=0.47754, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_4', max=1), HTML(value='')))

dev_4: time=0:00:13.195821, step=5475, loss=2.22604, exact_match=0.402365, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_5', max=1), HTML(value='')))

train_5: time=0:04:11.995784, step=6570, loss=1.72137, exact_match=0.516844, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_5', max=1), HTML(value='')))

dev_5: time=0:00:12.938025, step=6570, loss=2.21568, exact_match=0.414286, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_6', max=1), HTML(value='')))

train_6: time=0:04:12.075426, step=7665, loss=1.57074, exact_match=0.549709, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_6', max=1), HTML(value='')))

dev_6: time=0:00:13.100132, step=7665, loss=2.24416, exact_match=0.423084, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_7', max=1), HTML(value='')))

train_7: time=0:04:12.490949, step=8760, loss=1.43671, exact_match=0.581182, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_7', max=1), HTML(value='')))

dev_7: time=0:00:13.139639, step=8760, loss=2.28878, exact_match=0.423746, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_8', max=1), HTML(value='')))

train_8: time=0:04:10.542980, step=9855, loss=1.30654, exact_match=0.611286, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='dev_8', max=1), HTML(value='')))

dev_8: time=0:00:12.975790, step=9855, loss=2.3454, exact_match=0.41807, precision=0, recall=0, F1=0


HBox(children=(IntProgress(value=1, bar_style='info', description='train_9', max=1), HTML(value='')))

In [18]:
sess.run(
    model._dataset_iterator.initializer,
    feed_dict = {
        model._dataset_filenames: train_set[:1],
        model._dataset_limit: 10 })

In [20]:
contexts, context_lens, questions, question_lens = sess.run(
    [model._contexts,
     model._context_lens,
     model._questions,
     model._question_lens],
    feed_dict = { model._training: False })

In [23]:
context_lens

array([171,  70, 131, 102,  93, 190, 155, 129, 120, 162], dtype=int32)

In [57]:
answer_end_estimates

array([ 29,   5,  78,  43,  34,  25, 124, 117,  55, 110])

In [58]:
answer_starts[:, 0]

array([ 65,   4,  78,  49,  80, 181, 123, 117,  52, 110])

In [59]:
answer_ends[:, 0]

array([ 67,   5,  78,  49,  80, 189, 124, 117,  55, 110])

In [18]:
sess = reset_tf(sess)

In [23]:
gru = tf.contrib.cudnn_rnn.CudnnGRU(
    num_layers = 1,
    num_units = 50,
    input_size = 100,
    direction = 'bidirectional')

In [46]:
sess.run(tf.global_variables_initializer())

In [66]:
gru.params_size().eval(session = sess)

45600

In [29]:
gru_params = tf.get_variable(
    'gru_params',
    [gru.params_size().eval()])

In [57]:
input_h = tf.cast(np.random.rand(2, 30, 50), tf.float32)

In [53]:
input_data = tf.cast(np.random.rand(20, 30, 100), tf.float32)

In [49]:
input.shape

TensorShape([Dimension(20), Dimension(30), Dimension(100)])

In [58]:
result = gru(input_data, input_h, gru_params)

In [59]:
result

(<tf.Tensor 'CudnnRNN_5:0' shape=(20, 30, 100) dtype=float32>,
 <tf.Tensor 'CudnnRNN_5:1' shape=(2, 30, 50) dtype=float32>)

In [61]:
result[0].eval().shape

(20, 30, 100)

In [22]:
help(tf.contrib.cudnn_rnn.CudnnGRU)

Help on class CudnnGRU in module tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops:

class CudnnGRU(_CudnnRNNNoInputC)
 |  Cudnn implementation of the GRU model.
 |  Cudnn RNN has an opaque parameter buffer that can be used for inference and
 |  training. But it is possible that the layout of the parameter buffers
 |  changes between generations. So it is highly recommended to use
 |  CudnnOpaqueParamsSaveable to save and restore weights and biases in a
 |  canonical format.
 |  
 |  This is a typical use case:
 |  
 |    * The user creates a CudnnRNN model.
 |    * The user query that parameter buffer size.
 |    * The user creates a variable of that size that serves as the parameter
 |        buffers.
 |    * The user either initialize the parameter buffer, or load the canonical
 |        weights into the parameter buffer.
 |    * The user calls the model with the parameter buffer for inference, or
 |        training.
 |    * If training, the user creates a Saver object.
 |    * 

In [73]:
tf.tile(tf.reshape(tf.range(2*4), [2, 1, 4]), [1, 3, 1]).eval()[:, 1, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]], dtype=int32)

In [75]:
tf.expand_dims(tf.reshape(tf.range(2*4), [2, 4]), 1)

<tf.Tensor 'ExpandDims:0' shape=(2, 1, 4) dtype=int32>

In [3]:
sess = tf.InteractiveSession()

In [6]:
x = tf.reshape(tf.range(2*4), [2, 4])

In [10]:
x[:, :2].eval(), x[:, 2:].eval()

(array([[0, 1],
        [4, 5]], dtype=int32), array([[2, 3],
        [6, 7]], dtype=int32))

In [9]:
x.eval()

array([[0, 1, 2, 3],
       [4, 5, 6, 7]], dtype=int32)

In [12]:
def foo(x, y = 2*x):
    return y

In [14]:
foo(2)

<tf.Tensor 'mul:0' shape=(2, 4) dtype=int32>

In [11]:
gru = tf.contrib.cudnn_rnn.CudnnGRU(
    num_layers = 1,
    num_units = 10,
    input_size = 10,
    dropout = 0.5,
    direction = 'bidirectional')

In [12]:
gru.params_size().eval()

1320